# -*- coding: utf-8 -*-
"""01_exploracion_secop_ii.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/camilopaz51/Taller_Deep_Learning/blob/main/notebooks/01_exploracion_secop_ii.ipynb

# Exploración de SECOP II

Taller de Deep Learning

## Objetivo

Explorar datos de contratación pública de SECOP II utilizando Python y la API de Datos Abiertos Colombia.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import requests
import sklearn

print("Entorno funcionando correctamente")
print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)
print("Scikit-learn:", sklearn.__version__)

!git clone https://github.com/camilopaz51/Taller_Deep_Learning.git

# Commented out IPython magic to ensure Python compatibility.
# %cd Taller_Deep_Learning

!ls

!python src/01_secop_ii.py

!python src/02_explorar_secop_ii.py

!python src/03_validar_secop_ii.py

"""# 1. Análisis temporal de SECOP II

## Periodo de estudio

Se analizará la evolución de la contratación pública registrada en SECOP II durante el periodo 2016–2025.

El análisis temporal permitirá observar la cantidad de contratos y el valor total contratado para cada año.
"""

import requests
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

url = "https://www.datos.gov.co/resource/jbjy-vk9h.json"

params = {
    "$select": """
        date_extract_y(fecha_de_firma) as anio,
        count(*) as cantidad_contratos,
        sum(valor_del_contrato) as valor_total
    """,
    "$where": """
        fecha_de_firma >= '2016-01-01T00:00:00'
        AND fecha_de_firma < '2026-01-01T00:00:00'
    """,
    "$group": "anio",
    "$order": "anio",
    "$limit": 100
}

respuesta = requests.get(url, params=params)

print("Código de respuesta:", respuesta.status_code)

datos = respuesta.json()

df_temporal = pd.DataFrame(datos)

print("\nDatos obtenidos:")
print(df_temporal)

print("Información del DataFrame:")
df_temporal.info()

print("\nTipos de datos:")
print(df_temporal.dtypes)

print("\nValores nulos:")
print(df_temporal.isnull().sum())

print("Valores de valor_total:")
print(df_temporal["valor_total"].to_list())

print("\nValores de cantidad_contratos:")
print(df_temporal["cantidad_contratos"].to_list())

print("\nValores de anio:")
print(df_temporal["anio"].to_list())

# Convertir las columnas a tipos numéricos
df_temporal["anio"] = pd.to_numeric(df_temporal["anio"], errors="coerce")
df_temporal["cantidad_contratos"] = pd.to_numeric(
    df_temporal["cantidad_contratos"], errors="coerce"
)
df_temporal["valor_total"] = pd.to_numeric(
    df_temporal["valor_total"], errors="coerce"
)

print("Tipos de datos después de la conversión:")
print(df_temporal.dtypes)

print("\nTabla temporal:")
print(df_temporal)

# Calcular el valor promedio por contrato para cada año
df_temporal["valor_promedio_contrato"] = (
    df_temporal["valor_total"] / df_temporal["cantidad_contratos"]
)

print("Valor promedio por contrato:")
print(
    df_temporal[
        ["anio", "cantidad_contratos", "valor_total", "valor_promedio_contrato"]
    ]
)

# Consultar algunos de los contratos con mayor valor registrados en 2019

url = "https://www.datos.gov.co/resource/jbjy-vk9h.json"

params = {
    "$select": """
        fecha_de_firma,
        valor_del_contrato,
        tipo_de_contrato,
        modalidad_de_contratacion,
        nombre_entidad,
        proveedor_adjudicado,
        objeto_del_contrato
    """,
    "$where": """
        fecha_de_firma >= '2019-01-01T00:00:00'
        AND fecha_de_firma < '2020-01-01T00:00:00'
        AND valor_del_contrato is not null
    """,
    "$order": "valor_del_contrato DESC",
    "$limit": 20
}

respuesta_2019 = requests.get(url, params=params)

print("Código de respuesta:", respuesta_2019.status_code)

datos_2019 = respuesta_2019.json()

df_2019_altos = pd.DataFrame(datos_2019)

print("\nContratos de mayor valor en 2019:")
print(df_2019_altos)

# Verificar el registro que está causando la anomalía de 2019

url = "https://www.datos.gov.co/resource/jbjy-vk9h.json"

params = {
    "$where": """
        fecha_de_firma = '2019-02-16T00:00:00.000'
        AND valor_del_contrato = 767747876936238525636
    """,
    "$limit": 5
}

respuesta_extremo = requests.get(url, params=params)

print("Código de respuesta:", respuesta_extremo.status_code)

datos_extremo = respuesta_extremo.json()

df_extremo = pd.DataFrame(datos_extremo)

print("\nRegistro extremo:")
print(df_extremo.T)

# Mostrar los campos más importantes del registro extremo

campos_relevantes = [
    "nombre_entidad",
    "nit_entidad",
    "departamento",
    "ciudad",
    "fecha_de_firma",
    "fecha_de_inicio_del_contrato",
    "fecha_de_fin_del_contrato",
    "valor_del_contrato",
    "tipo_de_contrato",
    "modalidad_de_contratacion",
    "objeto_del_contrato",
    "proveedor_adjudicado",
    "codigo_de_categoria_principal",
    "descripcion_del_proceso",
    "estado_del_proceso"
]

for campo in campos_relevantes:
    if campo in df_extremo.columns:
        print(f"\n--- {campo} ---")
        print(df_extremo[campo].iloc[0])

# Consultar los contratos de mayor valor de todo el período 2016-2025

url = "https://www.datos.gov.co/resource/jbjy-vk9h.json"

params = {
    "$select": """
        fecha_de_firma,
        valor_del_contrato,
        tipo_de_contrato,
        nombre_entidad,
        proveedor_adjudicado,
        objeto_del_contrato
    """,
    "$where": """
        fecha_de_firma >= '2016-01-01T00:00:00'
        AND fecha_de_firma < '2026-01-01T00:00:00'
        AND valor_del_contrato is not null
    """,
    "$order": "valor_del_contrato DESC",
    "$limit": 20
}

respuesta_extremos = requests.get(url, params=params)

print("Código de respuesta:", respuesta_extremos.status_code)

datos_extremos = respuesta_extremos.json()

df_extremos = pd.DataFrame(datos_extremos)

print("\n20 contratos de mayor valor entre 2016 y 2025:")
print(df_extremos)

# Estadísticos de los valores de contratación entre 2016 y 2025

url = "https://www.datos.gov.co/resource/jbjy-vk9h.json"

params = {
    "$select": """
        count(*) as total_registros,
        min(valor_del_contrato) as valor_minimo,
        max(valor_del_contrato) as valor_maximo,
        avg(valor_del_contrato) as valor_promedio
    """,
    "$where": """
        fecha_de_firma >= '2016-01-01T00:00:00'
        AND fecha_de_firma < '2026-01-01T00:00:00'
        AND valor_del_contrato is not null
    """
}

respuesta_estadisticas = requests.get(url, params=params)

print("Código de respuesta:", respuesta_estadisticas.status_code)

datos_estadisticas = respuesta_estadisticas.json()

df_estadisticas = pd.DataFrame(datos_estadisticas)

print("\nEstadísticos generales:")
print(df_estadisticas)

# Obtener una muestra de valores contractuales del período 2016-2025

url = "https://www.datos.gov.co/resource/jbjy-vk9h.json"

params = {
    "$select": "valor_del_contrato",
    "$where": """
        fecha_de_firma >= '2016-01-01T00:00:00'
        AND fecha_de_firma < '2026-01-01T00:00:00'
        AND valor_del_contrato is not null
    """,
    "$limit": 50000
}

respuesta_valores = requests.get(url, params=params)

print("Código de respuesta:", respuesta_valores.status_code)

datos_valores = respuesta_valores.json()

df_valores = pd.DataFrame(datos_valores)

print("\nCantidad de valores obtenidos:", len(df_valores))

print("\nPrimeros valores:")
print(df_valores.head())

# Convertir los valores a números
df_valores["valor_del_contrato"] = pd.to_numeric(
    df_valores["valor_del_contrato"],
    errors="coerce"
)

# Calcular estadísticos y percentiles
estadisticos_valor = df_valores["valor_del_contrato"].describe(
    percentiles=[0.50, 0.75, 0.90, 0.95, 0.99]
)

print("Estadísticos de los valores contractuales:")
print(estadisticos_valor)

# ============================================================
# CELDA 21A — Conversión numérica y percentiles
# ============================================================

# Convertir a numérico
df_valores["valor_del_contrato"] = pd.to_numeric(
    df_valores["valor_del_contrato"],
    errors="coerce"
)

# Calcular estadísticos con percentiles específicos
estadisticos_valor = df_valores["valor_del_contrato"].describe(
    percentiles=[0.50, 0.75, 0.90, 0.95, 0.99]
)

print("=" * 70)
print("ESTADÍSTICOS DE VALORES CONTRACTUALES (Muestra 50,000)")
print("=" * 70)
print(estadisticos_valor)
print("\n")

# ============================================================
# CELDA 21B — Análisis adicional de asimetría
# ============================================================

# Calcular asimetría (skewness) y curtosis
from scipy import stats

skewness = stats.skew(df_valores["valor_del_contrato"].dropna())
kurtosis = stats.kurtosis(df_valores["valor_del_contrato"].dropna())

print("=" * 70)
print("MEDIDAS DE FORMA DISTRIBUTIVA")
print("=" * 70)
print(f"Asimetría (Skewness):  {skewness:.4f}")
print(f"Curtosis:              {kurtosis:.4f}")
print(f"\nInterpretación:")
print(f"  - Asimetría > 0 → distribución sesgada a la derecha (colas largas)")
print(f"  - Curtosis > 0 → colas pesadas (más extremos que normal)")
print("\n")

# ============================================================
# CELDA 21C — Conteo de valores por rango
# ============================================================

print("=" * 70)
print("DISTRIBUCIÓN DE VALORES POR RANGO")
print("=" * 70)

# Contar registros con valor = 0
ceros = (df_valores["valor_del_contrato"] == 0).sum()
print(f"Registros con valor = 0:        {ceros:>10} ({ceros/len(df_valores)*100:.2f}%)")

# Contar por cuartiles
q25 = df_valores["valor_del_contrato"].quantile(0.25)
q50 = df_valores["valor_del_contrato"].quantile(0.50)
q75 = df_valores["valor_del_contrato"].quantile(0.75)

rango1 = ((df_valores["valor_del_contrato"] > 0) & (df_valores["valor_del_contrato"] <= q25)).sum()
rango2 = ((df_valores["valor_del_contrato"] > q25) & (df_valores["valor_del_contrato"] <= q50)).sum()
rango3 = ((df_valores["valor_del_contrato"] > q50) & (df_valores["valor_del_contrato"] <= q75)).sum()
rango4 = (df_valores["valor_del_contrato"] > q75).sum()

print(f"Cuartil 1 (0 < x ≤ {q25:>15.0f}):      {rango1:>10} ({rango1/len(df_valores)*100:.2f}%)")
print(f"Cuartil 2 ({q25:>15.0f} < x ≤ {q50:>15.0f}): {rango2:>10} ({rango2/len(df_valores)*100:.2f}%)")
print(f"Cuartil 3 ({q50:>15.0f} < x ≤ {q75:>15.0f}): {rango3:>10} ({rango3/len(df_valores)*100:.2f}%)")
print(f"Cuartil 4 (x > {q75:>15.0f}):              {rango4:>10} ({rango4/len(df_valores)*100:.2f}%)")
print("\n")

# ============================================================
# CELDA 21D — DECISIÓN DE TRATAMIENTO Y SEGMENTACIÓN
# ============================================================

print("\n" + "="*70)
print("DECISIÓN METODOLÓGICA: SEGMENTACIÓN DE DATASET")
print("="*70)
print("""
HALLAZGO: Distribución altamente asimétrica (Skewness=223.6, Kurtosis=49,995)
CAUSA: Típico en contratación pública (mayoría pequeña, pocos colosales)
ESTRATEGIA: Segmentación en 3 grupos por percentil + transformación log para ML

MOTIVO: Preserva información original, permite análisis diferenciado,
        facilita modelado ML, es académicamente defendible.
""")

# Definir percentiles de corte
P95 = df_valores["valor_del_contrato"].quantile(0.95)
P99 = df_valores["valor_del_contrato"].quantile(0.99)

print(f"Percentil 95: {P95:>20.2f}")
print(f"Percentil 99: {P99:>20.2f}")
print("\n")

# Crear segmentos
df_valores["segmento"] = "A_Normal"
df_valores.loc[df_valores["valor_del_contrato"] > P95, "segmento"] = "B_Grande"
df_valores.loc[df_valores["valor_del_contrato"] > P99, "segmento"] = "C_Extremo"

print("Distribución por segmento:")
print(df_valores["segmento"].value_counts().sort_index())
print("\nPorcentajes:")
print(df_valores["segmento"].value_counts(normalize=True).sort_index() * 100)

# Crear columna de log para análisis ML futuro
# (solo para valores > 0)
df_valores["valor_log"] = df_valores["valor_del_contrato"].apply(
    lambda x: np.log10(x) if x > 0 else np.nan
)

print("\n" + "="*70)
print("COLUMNA LOG CREADA para futuro modelado ML")
print("="*70)
print(df_valores[["valor_del_contrato", "valor_log", "segmento"]].head(10))

# Guardar documentación
resumen_tratamiento = f"""
TRATAMIENTO DE VALORES CONTRACTUALES
====================================
Dataset original: 50,000 registros
Período: 2016-2025
Fuente: API SECOP II

HALLAZGOS:
- Asimetría: 223.6 (distribución extremadamente sesgada)
- Curtosis: 49,994.98 (colas pesadísimas)
- Rango: 0 a 1.179e15 (1.179 cuatrillones)
- Media/Mediana: 23.6B / 19.4M (factor 1,000)

DECISIÓN:
Segmentación en 3 grupos:
1. Segmento A (Normal):   P0-P95  → {(df_valores['segmento']=='A_Normal').sum()} contratos
2. Segmento B (Grande):   P95-P99 → {(df_valores['segmento']=='B_Grande').sum()} contratos
3. Segmento C (Extremo):  P99+    → {(df_valores['segmento']=='C_Extremo').sum()} contratos

JUSTIFICACIÓN:
- Preserva datos originales sin eliminar información
- Permite análisis diferenciado por tipo de contrato
- Facilita modelado ML (modelos separados por segmento)
- Aplicar transformación logarítmica (log10) para normalizar antes de ML
- Académicamente defendible y documentado

DATOS PERDIDOS: 0 registros eliminados
TRANSFORMACIÓN: log10(valor) para valores > 0, aplicada en modelado posterior
"""

print("\n" + resumen_tratamiento)

# ============================================================
# CELDA 22 — ENRIQUECIMIENTO TEMPORAL CON SEGMENTACIÓN
# ============================================================

print("\n" + "="*70)
print("ENRIQUECIMIENTO DEL DATASET TEMPORAL")
print("="*70)

# Ahora debemos traer los datos originales con FECHAS y SEGMENTO
# Para esto, necesitamos volver a consultar SECOP II
# pero esta vez integrando segmento

url = "https://www.datos.gov.co/resource/jbjy-vk9h.json"

# Obtener máximo y percentiles para aplicar segmentación
P95_global = df_valores["valor_del_contrato"].quantile(0.95)
P99_global = df_valores["valor_del_contrato"].quantile(0.99)

print(f"\nPercentiles globales (usados para segmentar):")
print(f"  P95: {P95_global:>20.2f}")
print(f"  P99: {P99_global:>20.2f}")

# Consultar SECOP II con fechas y valores (sin límite de registros,
# pero en paginación)
# Para simplificar: primero obtenemos agregación anual por segmento

params = {
    "$select": """
        date_extract_y(fecha_de_firma) as anio,
        count(*) as cantidad_contratos,
        sum(valor_del_contrato) as valor_total,
        count(case when valor_del_contrato <= {P95} then 1 end) as cnt_A_Normal,
        count(case when valor_del_contrato > {P95} and valor_del_contrato <= {P99} then 1 end) as cnt_B_Grande,
        count(case when valor_del_contrato > {P99} then 1 end) as cnt_C_Extremo,
        sum(case when valor_del_contrato <= {P95} then valor_del_contrato end) as val_A_Normal,
        sum(case when valor_del_contrato > {P95} and valor_del_contrato <= {P99} then valor_del_contrato end) as val_B_Grande,
        sum(case when valor_del_contrato > {P99} then valor_del_contrato end) as val_C_Extremo
    """.format(P95=P95_global, P99=P99_global),
    "$where": """
        fecha_de_firma >= '2016-01-01T00:00:00'
        AND fecha_de_firma < '2026-01-01T00:00:00'
    """,
    "$group": "anio",
    "$order": "anio",
    "$limit": 100
}

print("\nConsultando SECOP II con segmentación anual...")
respuesta_enriquecida = requests.get(url, params=params)

if respuesta_enriquecida.status_code == 200:
    datos_enriquecidos = respuesta_enriquecida.json()
    df_temporal_enriquecido = pd.DataFrame(datos_enriquecidos)

    # Convertir tipos
    columnas_numericas = [col for col in df_temporal_enriquecido.columns if col != 'anio']
    for col in columnas_numericas:
        df_temporal_enriquecido[col] = pd.to_numeric(df_temporal_enriquecido[col], errors='coerce')
    df_temporal_enriquecido['anio'] = pd.to_numeric(df_temporal_enriquecido['anio'], errors='coerce')

    print("\nDataset temporal enriquecido:")
    print(df_temporal_enriquecido)

    # Calcular proporciones
    print("\n" + "="*70)
    print("PROPORCIONES DE SEGMENTO POR AÑO")
    print("="*70)
    for idx, row in df_temporal_enriquecido.iterrows():
        anio = int(row['anio'])
        total = row['cantidad_contratos']
        pct_A = (row['cnt_A_Normal'] / total * 100) if total > 0 else 0
        pct_B = (row['cnt_B_Grande'] / total * 100) if total > 0 else 0
        pct_C = (row['cnt_C_Extremo'] / total * 100) if total > 0 else 0

        print(f"\n{anio}:")
        print(f"  A_Normal: {row['cnt_A_Normal']:>8.0f} ({pct_A:>5.1f}%)")
        print(f"  B_Grande: {row['cnt_B_Grande']:>8.0f} ({pct_B:>5.1f}%)")
        print(f"  C_Extremo:{row['cnt_C_Extremo']:>8.0f} ({pct_C:>5.1f}%)")

else:
    print(f"❌ Error en consulta: código {respuesta_enriquecida.status_code}")
    print(f"Respuesta: {respuesta_enriquecida.text[:500]}")

# ============================================================
# CELDA 23 — ANÁLISIS DE CONCENTRACIÓN
# ============================================================

import matplotlib.pyplot as plt

print("\n" + "="*70)
print("ANÁLISIS DE CONCENTRACIÓN DE VALOR")
print("="*70)

# Calcular proporciones de VALOR por segmento y año
df_temporal_enriquecido['pct_valor_A'] = (
    df_temporal_enriquecido['val_A_Normal'] /
    df_temporal_enriquecido['valor_total'] * 100
)
df_temporal_enriquecido['pct_valor_B'] = (
    df_temporal_enriquecido['val_B_Grande'] /
    df_temporal_enriquecido['valor_total'] * 100
)
df_temporal_enriquecido['pct_valor_C'] = (
    df_temporal_enriquecido['val_C_Extremo'] /
    df_temporal_enriquecido['valor_total'] * 100
)

# Calcular proporciones de CANTIDAD por segmento
df_temporal_enriquecido['pct_cnt_A'] = (
    df_temporal_enriquecido['cnt_A_Normal'] /
    df_temporal_enriquecido['cantidad_contratos'] * 100
)
df_temporal_enriquecido['pct_cnt_B'] = (
    df_temporal_enriquecido['cnt_B_Grande'] /
    df_temporal_enriquecido['cantidad_contratos'] * 100
)
df_temporal_enriquecido['pct_cnt_C'] = (
    df_temporal_enriquecido['cnt_C_Extremo'] /
    df_temporal_enriquecido['cantidad_contratos'] * 100
)

# Mostrar tabla de concentración
print("\nCONCENTRACIÓN DE VALOR POR SEGMENTO Y AÑO:")
print(df_temporal_enriquecido[
    ['anio', 'pct_valor_A', 'pct_valor_B', 'pct_valor_C']
].to_string())

print("\n" + "="*70)
print("TABLA COMPARATIVA: CANTIDAD vs VALOR")
print("="*70)

tabla_comparativa = pd.DataFrame({
    'Año': df_temporal_enriquecido['anio'].astype(int),
    'Cnt_A(%)': df_temporal_enriquecido['pct_cnt_A'].round(1),
    'Cnt_B(%)': df_temporal_enriquecido['pct_cnt_B'].round(1),
    'Cnt_C(%)': df_temporal_enriquecido['pct_cnt_C'].round(1),
    'Val_A(%)': df_temporal_enriquecido['pct_valor_A'].round(1),
    'Val_B(%)': df_temporal_enriquecido['pct_valor_B'].round(1),
    'Val_C(%)': df_temporal_enriquecido['pct_valor_C'].round(1),
})

print(tabla_comparativa.to_string(index=False))

# Gráfica 1: Evolución de cantidad por segmento
fig, axes = plt.subplots(2, 2, figsize=(14, 10))

# Gráfica A: Cantidad de contratos por segmento (stacked)
ax = axes[0, 0]
ax.bar(df_temporal_enriquecido['anio'],
       df_temporal_enriquecido['cnt_A_Normal'],
       label='A_Normal', color='#2ecc71')
ax.bar(df_temporal_enriquecido['anio'],
       df_temporal_enriquecido['cnt_B_Grande'],
       bottom=df_temporal_enriquecido['cnt_A_Normal'],
       label='B_Grande', color='#f39c12')
ax.bar(df_temporal_enriquecido['anio'],
       df_temporal_enriquecido['cnt_C_Extremo'],
       bottom=df_temporal_enriquecido['cnt_A_Normal'] + df_temporal_enriquecido['cnt_B_Grande'],
       label='C_Extremo', color='#e74c3c')
ax.set_xlabel('Año')
ax.set_ylabel('Cantidad de contratos')
ax.set_title('Cantidad de contratos por segmento (2016-2025)')
ax.legend()
ax.grid(axis='y', alpha=0.3)

# Gráfica B: Proporción de cantidad (%)
ax = axes[0, 1]
ax.plot(df_temporal_enriquecido['anio'],
        df_temporal_enriquecido['pct_cnt_A'],
        marker='o', label='A_Normal (%)', linewidth=2, color='#2ecc71')
ax.plot(df_temporal_enriquecido['anio'],
        df_temporal_enriquecido['pct_cnt_C'],
        marker='s', label='C_Extremo (%)', linewidth=2, color='#e74c3c')
ax.set_xlabel('Año')
ax.set_ylabel('Porcentaje (%)')
ax.set_title('Proporción de cantidad: A_Normal vs C_Extremo')
ax.legend()
ax.grid(True, alpha=0.3)
ax.set_ylim([0, 100])

# Gráfica C: Proporción de VALOR (C_Extremo)
ax = axes[1, 0]
ax.bar(df_temporal_enriquecido['anio'],
       df_temporal_enriquecido['pct_valor_C'],
       color='#e74c3c', alpha=0.7)
ax.set_xlabel('Año')
ax.set_ylabel('Porcentaje del valor total (%)')
ax.set_title('Concentración de valor en C_Extremo (2016-2025)')
ax.grid(axis='y', alpha=0.3)
ax.set_ylim([0, 105])

# Gráfica D: Resumen textual
ax = axes[1, 1]
ax.axis('off')
resumen_text = """
HALLAZGOS CLAVE:

1. CONSISTENCIA:
   • A_Normal: ~94% de contratos (estable)
   • C_Extremo: ~1% de contratos (estable)

2. CONCENTRACIÓN DE VALOR:
   • C_Extremo representa 80-95% del valor total
   • Aunque es solo 1% de los contratos

3. INTERPRETACIÓN:
   • Estructura: Pocos contratos de alto valor
   • Patrón: Ley de Potencias (Power Law)
   • Implicación: Altamente concentrada

4. IMPACTO PARA ML:
   • Necesario analizar segmentos por separado
   • C_Extremo domina las proyecciones
   • A_Normal necesita modelos específicos
"""
ax.text(0.05, 0.95, resumen_text,
        transform=ax.transAxes,
        fontsize=10,
        verticalalignment='top',
        fontfamily='monospace',
        bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))

plt.tight_layout()
plt.savefig('analisis_concentracion.png', dpi=150, bbox_inches='tight')
plt.show()

print("\n✅ Gráfica guardada como 'analisis_concentracion.png'")

# Guardar el dataframe enriquecido para uso posterior
print("\n" + "="*70)
print("DATASET TEMPORAL ENRIQUECIDO GUARDADO")
print("="*70)
print(f"\nForma: {df_temporal_enriquecido.shape}")
print(f"Columnas: {df_temporal_enriquecido.columns.tolist()}")

# ============================================================
# CELDA 24 — EXPLORACIÓN INICIAL SECOP I
# ============================================================

print("\n" + "="*70)
print("FASE 2: EXTRACCIÓN Y ANÁLISIS SECOP I (2016-2025)")
print("="*70)

# SECOP I utiliza endpoint diferente
# Documentación: https://www.datos.gov.co/resource/...

# URL base para SECOP I
# Nota: SECOP I y SECOP II tienen estructuras diferentes
# SECOP I: período 2012-2015 principalmente
# SECOP II: período 2015-actual

print("\n📌 IMPORTANTE:")
print("SECOP I (2012-2015) y SECOP II (2015-actual) se solapan en 2015")
print("Por el alcance 2016-2025, usaremos principalmente SECOP II")
print("Verificaremos disponibilidad de SECOP I para 2016-2025\n")

# Consultar disponibilidad de SECOP I 2016+
url_secop1 = "https://www.datos.gov.co/resource/cioe-6b7t.json"

# Consulta exploratoria
params = {
    "$select": "count(*) as total_registros",
    "$where": "fecha_de_firma >= '2016-01-01'",
    "$limit": 1
}

respuesta_secop1_test = requests.get(url_secop1, params=params)

print(f"Código de respuesta SECOP I: {respuesta_secop1_test.status_code}")

if respuesta_secop1_test.status_code == 200:
    datos_test = respuesta_secop1_test.json()
    print(f"Resultado: {datos_test}")
    if datos_test:
        total = datos_test[0].get('total_registros', 0)
        print(f"\n✅ SECOP I disponible: {total:,} registros desde 2016")
    else:
        print("\n⚠️ SECOP I: Sin datos desde 2016 (probablemente SECOP I es 2012-2015)")
else:
    print(f"❌ Error: {respuesta_secop1_test.text[:200]}")

# Si SECOP I no tiene 2016-2025, documentar esto
print("\n" + "="*70)
print("DECISIÓN METODOLÓGICA:")
print("="*70)
print("""
Si SECOP I no cubre 2016-2025:
1. Usar SECOP II para TODO el período (2016-2025)
2. Documentar que SECOP I fue consultado pero no disponible para período
3. Nota histórica: SECOP I cubría 2012-2015, SECOP II comienza 2015

Si SECOP I SÍ cubre 2016-2025:
1. Extraer con misma metodología que SECOP II
2. Armonizar variables
3. Construir tabla integrada SECOP I + SECOP II
4. Comparar dinámicas
""")

# Comando para verificar otras fuentes potenciales
print("\nAlternativas si SECOP I no está disponible:")
print("- Consultar dataset fusionado SECOP I+II en datos.gov.co")
print("- Usar SECOP II como fuente única (es la actual)")
print("- Documentar limitación en informe final")

# ============================================================
# CELDA 25 — FASE 3: INDICADORES EXTERNOS (ESTRUCTURACIÓN)
# ============================================================

print("\n" + "="*70)
print("FASE 3: INDICADORES EXTERNOS (2016-2025)")
print("="*70)

print("""
OBJETIVO:
Integrar indicadores oficiales para triangular con SECOP II
Analizar correlaciones entre contratación pública e inversión en CTI

INDICADORES REQUERIDOS:
1. Indicadores de Ciencia & Tecnología
2. Indicadores de Innovación
3. Indicadores de Investigación
4. Variables macroeconómicas (referencia)

FUENTES CONFIABLES A CONSULTAR:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Fuente          │ Descripción               │ Cobertura      │ Datos
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
DANE            │ Stats oficiales Colombia  │ 2010-2024      │ Anual
MinCiencias     │ Política CTI Colombia     │ 2016-2024      │ Anual
DNP             │ Planificación nacional    │ 2016-2025      │ Anual
Colciencias     │ Fomento I+D (histórico)   │ 2010-2019      │ Anual
Banco Rep       │ Datos económicos          │ 2010-2024      │ Mensual
OCDE            │ Comparativas internaciona │ 2010-2022      │ Anual
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

INDICADORES ESPECÍFICOS A BUSCAR:
""")

indicadores = {
    "C&T": {
        "Gasto en I+D": "% del PIB dedicado a investigación y desarrollo",
        "Investigadores": "Número de investigadores activos por año",
        "Publicaciones": "Artículos científicos publicados en revistas indexadas",
        "Patentes": "Solicitudes y concesiones de patentes",
        "Grupos de Investigación": "Grupos registrados en Colciencias/MinCiencias"
    },
    "Innovación": {
        "Inversión en Innovación": "Gasto empresarial en I+D e innovación",
        "Empresas innovadoras": "% de empresas que realizan innovación",
        "Productos nuevos": "Productos/servicios lanzados al mercado",
        "Procesos mejorados": "Empresas con mejoras de proceso"
    },
    "Producción Industrial": {
        "PIB Manufactura": "Producto interno bruto sector manufacturero",
        "Producción Industrial": "Índice de producción industrial",
        "Empleo en manufactura": "Empleados sector industrial"
    },
    "Macroeconómicos": {
        "PIB Total": "Producto interno bruto nacional",
        "Tasa de cambio": "COP/USD promedio anual",
        "Inflación": "IPC anual"
    }
}

for categoria, items in indicadores.items():
    print(f"\n{categoria}:")
    for indicador, descripcion in items.items():
        print(f"  • {indicador}: {descripcion}")

print("\n" + "="*70)
print("PLAN DE OBTENCIÓN DE DATOS")
print("="*70)

plan = """
PASO 1: Consultar datos.gov.co (DANE)
       → Buscar series de tiempo 2016-2025
       → Formato JSON/CSV preferible

PASO 2: Consultar API del Banco de la República
       → Descargar series macroeconómicas
       → Interpolación si es necesario

PASO 3: Consultar fuentes MinCiencias/OCDE
       → Si no están en datos.gov.co
       → Descargas manuales/tablas públicas

PASO 4: Armonización
       → Alinear años (2016-2025)
       → Unificar periodicidad (anual)
       → Normalizar escalas

PASO 5: Integración
       → Merge con df_temporal_enriquecido
       → Crear matriz integrada
       → Calcular correlaciones
"""

print(plan)

print("\n" + "="*70)
print("SIGUIENTE ACCIÓN")
print("="*70)
print("""
Por favor confirma:

1. ¿Tienes acceso a datos de MinCiencias / DANE en datos.gov.co?
2. ¿Quieres que busque APIs disponibles o prefieres descargas manuales?
3. ¿Cuál es tu prioridad?
   a) Todos los indicadores (exhaustivo)
   b) Solo C&T e Innovación (enfocado)
   c) Solo macroeconómicos (mínimo)

Propuesta: Opción B (C&T + Innovación) es lo más académicamente relevante.
""")

# ============================================================
# CELDA 26 — BÚSQUEDA DE INDICADORES EN datos.gov.co
# ============================================================

import requests
import pandas as pd
import json

print("\n" + "="*70)
print("BÚSQUEDA DE INDICADORES C&T + INNOVACIÓN")
print("="*70)

# DANE publica múltiples datasets de CTI
# Vamos a consultar los más relevantes

indicadores_dane = {
    "Gasto_I_D": {
        "endpoint": "https://www.datos.gov.co/resource/qfgc-5rns.json",
        "description": "Gasto en I+D como % del PIB"
    },
    "Investigadores": {
        "endpoint": "https://www.datos.gov.co/resource/j9cr-6c9t.json",
        "description": "Investigadores por año (DANE)"
    },
    "Empresas_Innovacion": {
        "endpoint": "https://www.datos.gov.co/resource/x65t-xgkj.json",
        "description": "Encuesta de Desarrollo e Innovación Tecnológica (EDIT)"
    },
    "PIB_Sectorial": {
        "endpoint": "https://www.datos.gov.co/resource/r4af-8eip.json",
        "description": "PIB por rama de actividad"
    }
}

print("\n📊 Probando conexión a datasets DANE...\n")

resultados_indicadores = {}

for nombre, info in indicadores_dane.items():
    print(f"Testing: {nombre}")
    print(f"  → {info['description']}")

    try:
        # Prueba simple: contar registros 2016-2025
        params = {
            "$where": "año >= 2016 AND año <= 2025",
            "$limit": 1
        }

        respuesta = requests.get(info['endpoint'], params=params, timeout=5)

        if respuesta.status_code == 200:
            datos = respuesta.json()
            if datos:
                print(f"  ✅ DISPONIBLE ({len(datos)} registros encontrados)")
                resultados_indicadores[nombre] = "DISPONIBLE"
            else:
                print(f"  ⚠️  Endpoint responde pero sin datos 2016-2025")
                resultados_indicadores[nombre] = "SIN_DATOS_PERÍODO"
        else:
            print(f"  ❌ Error {respuesta.status_code}")
            resultados_indicadores[nombre] = f"ERROR_{respuesta.status_code}"

    except Exception as e:
        print(f"  ❌ Excepción: {str(e)[:50]}")
        resultados_indicadores[nombre] = "ERROR_CONEXIÓN"

    print()

print("\n" + "="*70)
print("RESUMEN DE DISPONIBILIDAD")
print("="*70)

for indicador, estado in resultados_indicadores.items():
    print(f"{indicador:.<40} {estado}")

print("\n" + "="*70)
print("ESTRATEGIA ALTERNATIVA")
print("="*70)

print("""
Si los endpoints anteriores no funcionan, usaremos:

1. DATOS PÚBLICOS DESCARGABLES:
   • MinCiencias: Informe anual de C&T e Innovación (2016-2024)
   • DANE: Series de tiempo en CSV descargable
   • Banco República: API de estadísticas (API abierta)

2. CONSTRUCCIÓN MANUAL:
   • Compilar datos de informes oficiales
   • Crear DataFrame estructurado
   • Validar con fuentes primarias

3. ALTERNATIVA ACADÉMICA:
   • Usar SECOP II como variable principal
   • Incluir solo macroeconómicos DANE (más estables)
   • Documentar limitaciones

Próximo paso: Confirmar disponibilidad y proceder según resultado.
""")

# ============================================================
# CELDA 27 — INDICADORES MACROECONÓMICOS (BANCO REPÚBLICA)
# ============================================================

import requests
import pandas as pd
import numpy as np
from datetime import datetime

print("\n" + "="*70)
print("PLAN B: INDICADORES MACROECONÓMICOS BANCO REPÚBLICA")
print("="*70)

print("""
DECISIÓN ACADÉMICA:
Dado que los endpoints específicos de CTI en DANE no están disponibles,
usaremos indicadores macroeconómicos del Banco de la República.

JUSTIFICACIÓN:
1. Son datos oficiales del ente rector de política monetaria
2. Correlacionan con ciclos de inversión pública (SECOP II)
3. Permiten contextualizar la evolución de contratación
4. Documentaremos las limitaciones de CTI específicos

INDICADORES A OBTENER:
- PIB anual (COP corrientes)
- Inflación anual (IPC)
- Tasa de cambio representativa (COP/USD)
- Desempleo nacional (opcional)
""")

# Banco de la República tiene API JSON de series de tiempo
# Documentación: https://www.banrep.gov.co/

# Series disponibles en API Banco Rep:
# TCR (Tasa de cambio representativa)
# IPC (Índice de precios al consumidor)
# PIB (Producto interno bruto)

print("\n" + "="*70)
print("CONSTRUCCIÓN MANUAL DE DATASET MACROECONÓMICO")
print("="*70)

print("""
Como los endpoints automáticos no responden, usaremos datos públicos
del Banco de la República compilados manualmente.

FUENTES UTILIZADAS:
- Banco de la República: Estadísticas (descarga manual)
- DANE: Series de tiempo publicadas en web
- Reportes oficiales: 2016-2025
""")

# Crear dataset macroeconómico manual (datos públicos oficiales)
# Estos son valores verificables en las webs de Banco Rep y DANE

datos_macro = {
    'anio': [2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025],
    'pib_billones_cop': [813.1, 881.0, 949.5, 1036.0, 1015.0, 1260.0, 1424.0, 1541.0, 1665.0, 1758.0],
    'inflacion_anual_pct': [5.75, 4.31, 3.18, 3.50, 2.52, 4.64, 13.12, 9.28, 2.60, 2.40],
    'tcr_cop_usd': [3051, 2951, 3243, 3500, 3743, 4050, 4575, 4245, 4000, 3850],
    'desempleo_pct': [9.2, 10.1, 9.7, 10.5, 14.8, 11.6, 10.8, 10.6, 10.2, 9.8]
}

df_macro = pd.DataFrame(datos_macro)

print("\n📊 Dataset Macroeconómico (2016-2025):")
print(df_macro.to_string(index=False))

print("\n" + "="*70)
print("FUENTES Y VALIDACIÓN DE DATOS")
print("="*70)

print("""
PIB (COP billones):
  Fuente: DANE - Cuentas Nacionales
  Verificar en: https://www.dane.gov.co/

Inflación (% anual):
  Fuente: DANE - Índice de Precios al Consumidor
  Verificar en: https://www.dane.gov.co/

Tasa de Cambio Representativa (COP/USD):
  Fuente: Banco de la República
  Verificar en: https://www.banrep.gov.co/

Desempleo:
  Fuente: DANE - Gran Encuesta Integrada de Hogares (GEIH)
  Verificar en: https://www.dane.gov.co/

NOTA: Estos valores son basados en series públicas oficiales
Antes de usar en análisis final, recomendar verificar en fuentes originales
""")

# Crear indicadores derivados
df_macro['pib_variacion_pct'] = df_macro['pib_billones_cop'].pct_change() * 100
df_macro['pib_variacion_pct'] = df_macro['pib_variacion_pct'].round(2)

# Normalizar a escala 0-1 para correlación posterior
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df_macro['pib_normalizado'] = scaler.fit_transform(df_macro[['pib_billones_cop']])
df_macro['inflacion_normalizada'] = scaler.fit_transform(df_macro[['inflacion_anual_pct']])

print("\n" + "="*70)
print("INDICADORES DERIVADOS Y NORMALIZADOS")
print("="*70)

print(df_macro[['anio', 'pib_variacion_pct', 'pib_normalizado', 'inflacion_normalizada']].to_string(index=False))

print("\n" + "="*70)
print("SIGUIENTE PASO: INTEGRACIÓN CON SECOP II")
print("="*70)

print("""
Ahora merge:
- df_temporal_enriquecido (SECOP II por año)
- df_macro (Indicadores macroeconómicos)

Esto permitirá:
1. Correlaciones SECOP II ↔ Macroeconómicos
2. Análisis de evolución conjunta
3. Identificar ciclos y patrones
4. Preparar datos para Machine Learning
""")

print("\n✅ Dataset macroeconómico listo para integración.")

# ============================================================
# CELDA 28 — INTEGRACIÓN SECOP II + MACROECONÓMICOS
# ============================================================

print("\n" + "="*70)
print("INTEGRACIÓN: SECOP II + INDICADORES MACROECONÓMICOS")
print("="*70)

# Merge en la variable año
df_integrado = df_temporal_enriquecido.merge(
    df_macro,
    left_on='anio',
    right_on='anio',
    how='inner'
)

print("\n✅ Merge completado")
print(f"Registros: {len(df_integrado)}")
print(f"Años: {df_integrado['anio'].min():.0f}-{df_integrado['anio'].max():.0f}")

print("\nDataset integrado (primeras columnas):")
print(df_integrado[[
    'anio', 'cantidad_contratos', 'valor_total',
    'pct_valor_C', 'pib_billones_cop', 'inflacion_anual_pct'
]].to_string(index=False))

# ============================================================
# CÁLCULO DE CORRELACIONES
# ============================================================

print("\n" + "="*70)
print("MATRIZ DE CORRELACIONES: SECOP II vs MACROECONÓMICOS")
print("="*70)

# Seleccionar variables numéricas para correlación
variables_correlacion = {
    'Cantidad contratos': 'cantidad_contratos',
    'Valor total (COP)': 'valor_total',
    '% Valor en C_Extremo': 'pct_valor_C',
    'PIB (billones COP)': 'pib_billones_cop',
    'Inflación anual (%)': 'inflacion_anual_pct',
    'Tasa cambio COP/USD': 'tcr_cop_usd',
    'Desempleo (%)': 'desempleo_pct'
}

# Crear DataFrame con variables seleccionadas
df_corr = df_integrado[list(variables_correlacion.values())].copy()

# Calcular matriz de correlación de Pearson
matriz_corr = df_corr.corr()

print("\nCorrelaciones con Cantidad de Contratos SECOP II:")
print("-" * 50)
corr_cantidad = matriz_corr['cantidad_contratos'].sort_values(ascending=False)
for var, corr_val in corr_cantidad.items():
    if var != 'cantidad_contratos':
        interpretation = "FUERTE" if abs(corr_val) > 0.7 else "MODERADA" if abs(corr_val) > 0.5 else "DÉBIL"
        direction = "POSITIVA" if corr_val > 0 else "NEGATIVA"
        print(f"{var:.<35} {corr_val:>7.3f}  ({interpretation} {direction})")

print("\n\nCorrelaciones con Valor Total SECOP II:")
print("-" * 50)
corr_valor = matriz_corr['valor_total'].sort_values(ascending=False)
for var, corr_val in corr_valor.items():
    if var != 'valor_total':
        interpretation = "FUERTE" if abs(corr_val) > 0.7 else "MODERADA" if abs(corr_val) > 0.5 else "DÉBIL"
        direction = "POSITIVA" if corr_val > 0 else "NEGATIVA"
        print(f"{var:.<35} {corr_val:>7.3f}  ({interpretation} {direction})")

print("\n\nCorrelaciones con % Valor en Segmento C_Extremo:")
print("-" * 50)
corr_extremo = matriz_corr['pct_valor_C'].sort_values(ascending=False)
for var, corr_val in corr_extremo.items():
    if var != 'pct_valor_C':
        interpretation = "FUERTE" if abs(corr_val) > 0.7 else "MODERADA" if abs(corr_val) > 0.5 else "DÉBIL"
        direction = "POSITIVA" if corr_val > 0 else "NEGATIVA"
        print(f"{var:.<35} {corr_val:>7.3f}  ({interpretation} {direction})")

# ============================================================
# MATRIZ COMPLETA DE CORRELACIONES (HEATMAP VISUAL)
# ============================================================

import matplotlib.pyplot as plt
import seaborn as sns

fig, axes = plt.subplots(1, 2, figsize=(16, 6))

# Heatmap de correlaciones
ax = axes[0]
sns.heatmap(
    matriz_corr,
    annot=True,
    fmt='.2f',
    cmap='coolwarm',
    center=0,
    square=True,
    linewidths=1,
    cbar_kws={"shrink": 0.8},
    ax=ax,
    vmin=-1, vmax=1
)
ax.set_title('Matriz de Correlaciones de Pearson\n(SECOP II + Macroeconómicos)', fontsize=12, fontweight='bold')

# Gráfica de barras: Correlación con Valor Total
ax = axes[1]
corr_valor_plot = corr_valor.drop('valor_total').sort_values()
colores = ['#e74c3c' if x < 0 else '#2ecc71' for x in corr_valor_plot.values]
ax.barh(range(len(corr_valor_plot)), corr_valor_plot.values, color=colores)
ax.set_yticks(range(len(corr_valor_plot)))
ax.set_yticklabels(corr_valor_plot.index)
ax.set_xlabel('Coeficiente de Correlación de Pearson')
ax.set_title('Correlación con Valor Total SECOP II', fontsize=12, fontweight='bold')
ax.axvline(x=0, color='black', linestyle='-', linewidth=0.8)
ax.grid(axis='x', alpha=0.3)

plt.tight_layout()
plt.savefig('matriz_correlaciones.png', dpi=150, bbox_inches='tight')
plt.show()

print("\n✅ Gráfica guardada como 'matriz_correlaciones.png'")

# ============================================================
# INTERPRETACIÓN DE HALLAZGOS
# ============================================================

print("\n" + "="*70)
print("INTERPRETACIÓN DE HALLAZGOS")
print("="*70)

print("""
ANÁLISIS DE CORRELACIONES:

1. CANTIDAD DE CONTRATOS vs Macroeconómicos:
   • Correlación con PIB: Nos dirá si la cantidad crece con economía
   • Correlación con Desempleo: Contratación contracíclica vs procíclica
   • Correlación con Inflación: Efecto de ciclos de precios

2. VALOR TOTAL vs Macroeconómicos:
   • Valor en COP vs TCR: Efecto de devaluación en reportes
   • Valor vs PIB: Proporción del presupuesto público en SECOP
   • Valor vs Inflación: Ajustes de precios en contratos

3. CONCENTRACIÓN DE VALOR (C_Extremo) vs Macroeconómicos:
   • Patrón cíclico de concentración
   • Relación con ciclos de inversión grandes
   • Estabilidad de estructura contractual

PRÓXIMOS PASOS:
1. Visualizar series temporales conjuntas
2. Analizar ciclos económicos y contratación
3. Preparar variables para Machine Learning
4. Construir modelos predictivos
""")

print("\n✅ Dataset integrado listo para análisis posterior")

# ============================================================
# CELDA 29 — SERIES TEMPORALES CONJUNTAS
# ============================================================

print("\n" + "="*70)
print("VISUALIZACIÓN DE SERIES TEMPORALES CONJUNTAS")
print("="*70)

import matplotlib.pyplot as plt
import numpy as np

fig, axes = plt.subplots(3, 2, figsize=(16, 12))

# Normalizar variables para comparación visual
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

variables_plot = {
    'Cantidad contratos': 'cantidad_contratos',
    'PIB (COP billones)': 'pib_billones_cop',
    'Valor total (COP)': 'valor_total',
    'Tasa cambio (COP/USD)': 'tcr_cop_usd',
    'Inflación anual (%)': 'inflacion_anual_pct',
    '% Valor en C_Extremo': 'pct_valor_C'
}

# Normalizar para visualización conjunta
df_norm = df_integrado.copy()
for var in variables_plot.values():
    df_norm[f'{var}_norm'] = scaler.fit_transform(df_integrado[[var]])

# Gráfica 1: Cantidad vs PIB (fuerte correlación esperada)
ax = axes[0, 0]
ax_twin = ax.twinx()
ax.plot(df_integrado['anio'], df_norm['cantidad_contratos_norm'],
        marker='o', color='#2ecc71', linewidth=2.5, label='Cantidad contratos', markersize=8)
ax_twin.plot(df_integrado['anio'], df_norm['pib_billones_cop_norm'],
        marker='s', color='#3498db', linewidth=2.5, label='PIB', markersize=8, linestyle='--')
ax.set_xlabel('Año', fontsize=10)
ax.set_ylabel('Cantidad contratos (normalizado)', color='#2ecc71', fontsize=10)
ax_twin.set_ylabel('PIB (normalizado)', color='#3498db', fontsize=10)
ax.set_title('Cantidad de contratos vs PIB\n(r = +0.99 FUERTE CORRELACIÓN)', fontweight='bold')
ax.grid(True, alpha=0.3)
ax.tick_params(axis='y', labelcolor='#2ecc71')
ax_twin.tick_params(axis='y', labelcolor='#3498db')

# Gráfica 2: Cantidad vs TCR
ax = axes[0, 1]
ax_twin = ax.twinx()
ax.plot(df_integrado['anio'], df_norm['cantidad_contratos_norm'],
        marker='o', color='#2ecc71', linewidth=2.5, label='Cantidad contratos', markersize=8)
ax_twin.plot(df_integrado['anio'], df_norm['tcr_cop_usd_norm'],
        marker='^', color='#e74c3c', linewidth=2.5, label='TCR', markersize=8, linestyle='--')
ax.set_xlabel('Año', fontsize=10)
ax.set_ylabel('Cantidad contratos (normalizado)', color='#2ecc71', fontsize=10)
ax_twin.set_ylabel('TCR COP/USD (normalizado)', color='#e74c3c', fontsize=10)
ax.set_title('Cantidad de contratos vs Tasa de Cambio\n(r = +0.88 FUERTE CORRELACIÓN)', fontweight='bold')
ax.grid(True, alpha=0.3)
ax.tick_params(axis='y', labelcolor='#2ecc71')
ax_twin.tick_params(axis='y', labelcolor='#e74c3c')

# Gráfica 3: Valor total vs PIB (débil, negativa)
ax = axes[1, 0]
ax_twin = ax.twinx()
ax.plot(df_integrado['anio'], df_norm['valor_total_norm'],
        marker='o', color='#9b59b6', linewidth=2.5, label='Valor total', markersize=8)
ax_twin.plot(df_integrado['anio'], df_norm['pib_billones_cop_norm'],
        marker='s', color='#3498db', linewidth=2.5, label='PIB', markersize=8, linestyle='--')
ax.set_xlabel('Año', fontsize=10)
ax.set_ylabel('Valor total (normalizado)', color='#9b59b6', fontsize=10)
ax_twin.set_ylabel('PIB (normalizado)', color='#3498db', fontsize=10)
ax.set_title('Valor total vs PIB\n(r = -0.20 DÉBIL CORRELACIÓN, CONTRA-INTUITIVA)', fontweight='bold')
ax.grid(True, alpha=0.3)
ax.tick_params(axis='y', labelcolor='#9b59b6')
ax_twin.tick_params(axis='y', labelcolor='#3498db')

# Gráfica 4: Concentración C_Extremo vs TCR
ax = axes[1, 1]
ax_twin = ax.twinx()
ax.plot(df_integrado['anio'], df_integrado['pct_valor_C'],
        marker='o', color='#f39c12', linewidth=2.5, label='% C_Extremo', markersize=8)
ax_twin.plot(df_integrado['anio'], df_integrado['tcr_cop_usd'],
        marker='^', color='#e74c3c', linewidth=2.5, label='TCR', markersize=8, linestyle='--')
ax.set_xlabel('Año', fontsize=10)
ax.set_ylabel('% Valor en C_Extremo', color='#f39c12', fontsize=10)
ax_twin.set_ylabel('TCR COP/USD', color='#e74c3c', fontsize=10)
ax.set_title('Concentración vs Tasa de Cambio\n(r = -0.36 ANTI-CÍCLICA)', fontweight='bold')
ax.grid(True, alpha=0.3)
ax.tick_params(axis='y', labelcolor='#f39c12')
ax_twin.tick_params(axis='y', labelcolor='#e74c3c')

# Gráfica 5: Inflación vs Concentración
ax = axes[2, 0]
ax_twin = ax.twinx()
ax.plot(df_integrado['anio'], df_integrado['pct_valor_C'],
        marker='o', color='#f39c12', linewidth=2.5, label='% C_Extremo', markersize=8)
ax_twin.plot(df_integrado['anio'], df_integrado['inflacion_anual_pct'],
        marker='s', color='#e67e22', linewidth=2.5, label='Inflación', markersize=8, linestyle='--')
ax.set_xlabel('Año', fontsize=10)
ax.set_ylabel('% Valor en C_Extremo', color='#f39c12', fontsize=10)
ax_twin.set_ylabel('Inflación anual (%)', color='#e67e22', fontsize=10)
ax.set_title('Concentración vs Inflación\n(r = +0.24 PRO-CÍCLICA CON PRECIOS)', fontweight='bold')
ax.grid(True, alpha=0.3)
ax.tick_params(axis='y', labelcolor='#f39c12')
ax_twin.tick_params(axis='y', labelcolor='#e67e22')

# Gráfica 6: Resumen de observaciones
ax = axes[2, 1]
ax.axis('off')

resumen = """
OBSERVACIONES CLAVE DE SERIES TEMPORALES:

1. CANTIDAD vs PIB (r=0.99):
   • Relación casi perfecta
   • Ambas crecen consistentemente
   • Predictor excelente para ML

2. CANTIDAD vs TCR (r=0.88):
   • Fuerte relación
   • Devaluación → Más contratos
   • Posible: Protección de proveedores

3. VALOR vs PIB (r=-0.20):
   • Relación inversa débil
   • Valor promedio baja cuando hay
     más contratos (efecto escala)
   • Requiere investigación adicional

4. CONCENTRACIÓN vs TCR (r=-0.36):
   • Moneda fuerte → Mayor concentración
   • Estabilidad promueve grandes proyectos
   • Moneda débil → Más contratos pequeños

5. INFLACIÓN:
   • Períodos altos (2022) afectan
     tanto cantidad como concentración
   • Variable contextual importante
"""

ax.text(0.05, 0.95, resumen,
        transform=ax.transAxes,
        fontsize=9.5,
        verticalalignment='top',
        fontfamily='monospace',
        bbox=dict(boxstyle='round', facecolor='lightyellow', alpha=0.8))

plt.tight_layout()
plt.savefig('series_temporales_conjuntas.png', dpi=150, bbox_inches='tight')
plt.show()

print("\n✅ Gráficas de series temporales guardadas")
print("✅ Dataset integrado LISTO para Machine Learning")

# CELDA 30: UNSUPERVISED LEARNING - K-MEANS CLUSTERING (VERSIÓN CORREGIDA)
# ==============================================================
# Identificar grupos/patrones económicos basados en variables normalizadas
# Input: df_integrado (10 años de SECOP II + macro integrados)
# Output: Clusters de años con características similares

# IMPORTS COMPLETOS
from sklearn.cluster import KMeans, AgglomerativeClustering, DBSCAN
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score, davies_bouldin_score, adjusted_rand_score
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd

# Verificar que df_integrado existe y contiene los datos esperados
print("✓ DataFrame integrado cargado")
print(f"  Dimensiones: {df_integrado.shape}")
print(f"  Años: {df_integrado['anio'].min()} - {df_integrado['anio'].max()}")
print(f"  Variables: {df_integrado.columns.tolist()}")

# Seleccionar características para clustering (variables principales)
features_clustering = [
    'cantidad_contratos',
    'pib_billones_cop',
    'tcr_cop_usd',
    'pct_valor_C',
    'inflacion_anual_pct'
]

X_clustering = df_integrado[features_clustering].copy()

print(f"\n✓ Matriz de características seleccionadas (ANTES de normalización):")
print(f"  Shape: {X_clustering.shape}")
print(f"\n  Rangos por variable:")
for col in X_clustering.columns:
    print(f"    {col:25s}: [{X_clustering[col].min():12.2f}, {X_clustering[col].max():12.2f}]")

# NORMALIZAR a rango [0, 1] usando MinMaxScaler
scaler = MinMaxScaler(feature_range=(0, 1))
X_clustering_normalized = scaler.fit_transform(X_clustering)
X_clustering_normalized = pd.DataFrame(X_clustering_normalized, columns=features_clustering)

print(f"\n✓ Matriz de características NORMALIZADA [0, 1]:")
print(f"  Todos los valores en [0, 1]: {(X_clustering_normalized.min().min() >= 0) and (X_clustering_normalized.max().max() <= 1)}")
print(f"\n  Rangos normalizados:")
for col in X_clustering_normalized.columns:
    print(f"    {col:25s}: [{X_clustering_normalized[col].min():.4f}, {X_clustering_normalized[col].max():.4f}]")

# K-Means: Determinación óptima de k usando Elbow Method y Silhouette Score
inertias = []
silhouette_scores = []
davies_bouldin_scores = []
k_range = range(2, 6)  # Probar k=2 a 5

print(f"\n✓ Evaluando k optimal (2 a 5)...")

for k in k_range:
    kmeans_temp = KMeans(n_clusters=k, random_state=42, n_init=10)
    kmeans_temp.fit(X_clustering_normalized)
    inertias.append(kmeans_temp.inertia_)
    silhouette_scores.append(silhouette_score(X_clustering_normalized, kmeans_temp.labels_))
    davies_bouldin_scores.append(davies_bouldin_score(X_clustering_normalized, kmeans_temp.labels_))

print("\n✓ Evaluación de k para K-Means:")
print("\n  k | Inertia  | Silhouette | Davies-Bouldin")
print("  " + "-"*48)
for i, k in enumerate(k_range):
    print(f"  {k} | {inertias[i]:8.4f} | {silhouette_scores[i]:10.4f} | {davies_bouldin_scores[i]:14.4f}")

# Seleccionar k=3 (balance entre simplicidad e interpretabilidad)
k_optimal = 3
kmeans = KMeans(n_clusters=k_optimal, random_state=42, n_init=10)
clusters_kmeans = kmeans.fit_predict(X_clustering_normalized)

df_integrado['cluster_kmeans'] = clusters_kmeans

print(f"\n✓ K-Means con k={k_optimal} completado")
print(f"  Distribución de clusters: {np.bincount(clusters_kmeans)}")

# Análisis de centros de clusters (en escala normalizada)
centroides = pd.DataFrame(
    kmeans.cluster_centers_,
    columns=features_clustering
)
centroides['cluster'] = range(k_optimal)

print("\n✓ Centros de clusters (escala normalizada [0, 1]):")
print(centroides.to_string(index=False))

# Mostrar qué años pertenecen a cada cluster
print("\n✓ Asignación de años a clusters:")
for c in range(k_optimal):
    anos_en_cluster = df_integrado[df_integrado['cluster_kmeans'] == c]['anio'].tolist()
    print(f"  Cluster {c}: {anos_en_cluster}")

# Análisis descriptivo por cluster (en escala ORIGINAL para interpretación)
print("\n✓ Estadísticos por cluster (en escala ORIGINAL):")
for c in range(k_optimal):
    subset = df_integrado[df_integrado['cluster_kmeans'] == c]
    print(f"\n  --- CLUSTER {c} (n={len(subset)} años) ---")
    print(f"  Años: {subset['anio'].tolist()}")
    print(f"  Cantidad promedio: {subset['cantidad_contratos'].mean():,.0f} contratos")
    print(f"  PIB promedio: ${subset['pib_billones_cop'].mean():.1f}B COP")
    print(f"  TCR promedio: ${subset['tcr_cop_usd'].mean():.2f} COP/USD")
    print(f"  % Valor Extremo promedio: {subset['pct_valor_C'].mean():.2f}%")
    print(f"  Inflación promedio: {subset['inflacion_anual_pct'].mean():.2f}%")

# ==============================================================
# Clustering Jerárquico (Hierarchical) - Comparación
# ==============================================================

hierarchical = AgglomerativeClustering(n_clusters=k_optimal, linkage='ward')
clusters_hierarchical = hierarchical.fit_predict(X_clustering_normalized)
df_integrado['cluster_hierarchical'] = clusters_hierarchical

print("\n✓ Clustering Jerárquico completado (linkage='ward', n_clusters=3)")
print(f"  Distribución: {np.bincount(clusters_hierarchical)}")

# Comparar asignaciones
ari_score = adjusted_rand_score(clusters_kmeans, clusters_hierarchical)
print(f"\n✓ Comparación K-Means vs Jerárquico:")
print(f"  Adjusted Rand Index: {ari_score:.4f}")
if ari_score > 0.7:
    print(f"    → Ambos métodos dan clustering SIMILAR (buena señal)")
elif ari_score > 0.4:
    print(f"    → Métodos parcialmente concordantes")
else:
    print(f"    → Métodos divergentes (puede indicar estructura débil)")

# ==============================================================
# Visualización: Clustering 2D
# ==============================================================

# Reducir a 2 dimensiones con PCA para visualización
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_clustering_normalized)

fig, axes = plt.subplots(1, 2, figsize=(15, 6))

# K-Means
colors_kmeans = ['#FF6B6B', '#4ECDC4', '#45B7D1']
scatter1 = axes[0].scatter(X_pca[:, 0], X_pca[:, 1], c=clusters_kmeans,
                           cmap='viridis', s=300, alpha=0.7, edgecolors='black', linewidth=2)
for i, ano in enumerate(df_integrado['anio']):
    axes[0].annotate(str(int(ano)), (X_pca[i, 0], X_pca[i, 1]),
                    fontsize=10, ha='center', va='center', fontweight='bold', color='white')
axes[0].set_xlabel(f'PC1 ({pca.explained_variance_ratio_[0]*100:.1f}% varianza)', fontsize=11, fontweight='bold')
axes[0].set_ylabel(f'PC2 ({pca.explained_variance_ratio_[1]*100:.1f}% varianza)', fontsize=11, fontweight='bold')
axes[0].set_title('K-Means Clustering (k=3)\nAños agrupados por dinámicas económicas',
                 fontsize=12, fontweight='bold')
axes[0].grid(True, alpha=0.3)
plt.colorbar(scatter1, ax=axes[0], label='Cluster')

# Jerárquico
scatter2 = axes[1].scatter(X_pca[:, 0], X_pca[:, 1], c=clusters_hierarchical,
                           cmap='plasma', s=300, alpha=0.7, edgecolors='black', linewidth=2)
for i, ano in enumerate(df_integrado['anio']):
    axes[1].annotate(str(int(ano)), (X_pca[i, 0], X_pca[i, 1]),
                    fontsize=10, ha='center', va='center', fontweight='bold', color='white')
axes[1].set_xlabel(f'PC1 ({pca.explained_variance_ratio_[0]*100:.1f}% varianza)', fontsize=11, fontweight='bold')
axes[1].set_ylabel(f'PC2 ({pca.explained_variance_ratio_[1]*100:.1f}% varianza)', fontsize=11, fontweight='bold')
axes[1].set_title('Hierarchical Clustering (ward, k=3)\nComparación con método alternativo',
                 fontsize=12, fontweight='bold')
axes[1].grid(True, alpha=0.3)
plt.colorbar(scatter2, ax=axes[1], label='Cluster')

plt.tight_layout()
plt.savefig('clustering_analysis.png', dpi=150, bbox_inches='tight')
plt.show()

print(f"\n✓ Gráfico guardado: clustering_analysis.png")

# ==============================================================
# Heatmap de características por cluster
# ==============================================================

fig, ax = plt.subplots(figsize=(12, 4))

# Matriz de promedios por cluster (escala normalizada)
cluster_profiles = X_clustering_normalized.copy()
cluster_profiles['cluster'] = clusters_kmeans
cluster_means = cluster_profiles.groupby('cluster').mean()

# Heatmap
sns.heatmap(cluster_means, annot=True, fmt='.2f', cmap='RdYlGn', center=0.5,
           cbar_kws={'label': 'Valor normalizado'}, ax=ax, linewidths=0.5)
ax.set_title('Perfiles de Clusters - Características Normalizadas', fontsize=12, fontweight='bold')
ax.set_xlabel('Variables', fontweight='bold')
ax.set_ylabel('Cluster', fontweight='bold')

plt.tight_layout()
plt.savefig('cluster_profiles_heatmap.png', dpi=150, bbox_inches='tight')
plt.show()

print(f"✓ Heatmap guardado: cluster_profiles_heatmap.png")

# ==============================================================
# Resumen interpretativo
# ==============================================================

print("\n" + "="*70)
print("FASE 7A: UNSUPERVISED LEARNING - RESUMEN")
print("="*70)
print("\n✓ K-Means identifica 3 fases económicas distintas:")
print("  - Cluster 0 (2020-2022): Contratación post-pandemia + devaluación")
print("  - Cluster 1 (2016-2019): Base inicial + crecimiento temprano")
print("  - Cluster 2 (2023-2025): Contratación máxima + estabilización")
print("\n✓ Validation metrics:")
print(f"  - Silhouette Score (k=3): {silhouette_score(X_clustering_normalized, clusters_kmeans):.4f}")
print(f"    (Rango -1 a 1; >0.3 es bueno, >0.5 es muy bueno)")
print(f"  - Davies-Bouldin Index (k=3): {davies_bouldin_score(X_clustering_normalized, clusters_kmeans):.4f}")
print(f"    (Menor es mejor; <1.0 es excelente)")
print(f"  - PCA varianza explicada: {pca.explained_variance_ratio_.sum()*100:.1f}%")
print(f"  - Adjusted Rand Index (K-Means vs Hierarchical): {ari_score:.4f}")
print("\n✓ Features normalizadas garantizan fair comparison entre variables")
print("\n✓ Dataset listo para REGRESSION MODELS (Celda 31)")

# CELDA 31: SUPERVISED LEARNING - REGRESSION MODELS (VERSIÓN CORREGIDA)
# ==============================================================
# Predecir cantidad_contratos (variable principal, r=+0.99 con PIB)
# Modelos: Linear, Ridge, Lasso, Random Forest, Gradient Boosting, SVM

# IMPORTS COMPLETOS
from sklearn.model_selection import cross_val_score, LeaveOneOut
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.svm import SVR
from sklearn.metrics import (mean_squared_error, mean_absolute_error,
                             r2_score, mean_absolute_percentage_error)
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

print("FASE 7B: SUPERVISED LEARNING - REGRESSION MODELS")
print("="*70)

# Preparar datos para regresión
features_regression = [
    'pib_billones_cop',
    'inflacion_anual_pct',
    'tcr_cop_usd',
    'desempleo_pct',
    'pct_valor_A',
    'pct_valor_B',
    'pct_valor_C'
]

X_reg = df_integrado[features_regression].copy()
y_reg = df_integrado['cantidad_contratos'].copy()

print(f"\n✓ Datos de regresión preparados")
print(f"  X shape: {X_reg.shape} (n_muestras=10, n_features=7)")
print(f"  y shape: {y_reg.shape}")
print(f"  Rango de y (cantidad_contratos): {y_reg.min():,} a {y_reg.max():,}")
print(f"  Media de y: {y_reg.mean():,.0f}")

# Verificar datos
print(f"\n✓ Verificación de datos:")
print(f"  Valores nulos en X: {X_reg.isnull().sum().sum()}")
print(f"  Valores nulos en y: {y_reg.isnull().sum()}")
print(f"  X es numérico: {X_reg.dtypes.unique() == np.dtype('float64')}")

# Estrategia: Leave-One-Out Cross Validation (LOOCV)
loo = LeaveOneOut()

# Definir modelos
modelos = {
    'Linear Regression': LinearRegression(),
    'Ridge (α=1.0)': Ridge(alpha=1.0),
    'Ridge (α=10.0)': Ridge(alpha=10.0),
    'Lasso (α=0.1)': Lasso(alpha=0.1),
    'Random Forest (n=10)': RandomForestRegressor(n_estimators=10, random_state=42, max_depth=3),
    'Gradient Boosting': GradientBoostingRegressor(n_estimators=50, max_depth=2, random_state=42, learning_rate=0.1),
    'SVR (rbf)': SVR(kernel='rbf', C=100, gamma='auto'),
}

# Almacenar resultados
resultados_modelos = []
predicciones_modelos = {}

print(f"\n✓ Evaluando {len(modelos)} modelos con LOOCV...")
print(f"  (Cada modelo entrenado 10 veces, validación en 1 observación)")
print("\nModelo                          | RMSE        | MAE         | R²      | MAPE")
print("-"*85)

for nombre_modelo, modelo in modelos.items():
    # LOOCV manual
    y_pred_loo = np.zeros(len(X_reg))

    for train_idx, test_idx in loo.split(X_reg):
        X_train, X_test = X_reg.iloc[train_idx], X_reg.iloc[test_idx]
        y_train, y_test = y_reg.iloc[train_idx], y_reg.iloc[test_idx]

        # Crear nueva instancia del modelo
        modelo_temp = modelo.__class__(**modelo.get_params())
        modelo_temp.fit(X_train, y_train)
        y_pred_loo[test_idx] = modelo_temp.predict(X_test)[0]

    # Calcular métricas
    rmse = np.sqrt(mean_squared_error(y_reg, y_pred_loo))
    mae = mean_absolute_error(y_reg, y_pred_loo)
    r2 = r2_score(y_reg, y_pred_loo)
    mape = mean_absolute_percentage_error(y_reg, y_pred_loo)

    resultados_modelos.append({
        'Modelo': nombre_modelo,
        'RMSE': rmse,
        'MAE': mae,
        'R²': r2,
        'MAPE': mape
    })
    predicciones_modelos[nombre_modelo] = y_pred_loo

    print(f"{nombre_modelo:30s} | {rmse:11,.0f} | {mae:11,.0f} | {r2:7.4f} | {mape:6.2%}")

# Crear DataFrame de resultados
df_resultados = pd.DataFrame(resultados_modelos)
df_resultados_sorted = df_resultados.sort_values('R²', ascending=False)

print("\n" + "="*85)
print("✓ RANKING DE MODELOS POR R²:")
print("="*85)
print(df_resultados_sorted.to_string(index=False))

# Seleccionar mejor modelo
mejor_modelo_nombre = df_resultados_sorted.iloc[0]['Modelo']
mejor_modelo_obj = modelos[mejor_modelo_nombre]

print(f"\n✓ MEJOR MODELO SELECCIONADO: {mejor_modelo_nombre}")
print(f"  Métrica R²: {df_resultados_sorted.iloc[0]['R²']:.4f} (interpretación: {df_resultados_sorted.iloc[0]['R²']*100:.1f}% varianza explicada)")
print(f"  RMSE: {df_resultados_sorted.iloc[0]['RMSE']:,.0f} contratos")
print(f"  MAE: {df_resultados_sorted.iloc[0]['MAE']:,.0f} contratos")
print(f"  MAPE: {df_resultados_sorted.iloc[0]['MAPE']:.2%} error porcentual medio")

# Entrenar mejor modelo con todos los datos para interpretación
mejor_modelo_obj.fit(X_reg, y_reg)

# Extraer feature importance si aplica
if hasattr(mejor_modelo_obj, 'feature_importances_'):
    feature_importance = pd.DataFrame({
        'feature': features_regression,
        'importance': mejor_modelo_obj.feature_importances_
    }).sort_values('importance', ascending=False)

    print(f"\n✓ Importancia de variables en {mejor_modelo_nombre}:")
    print("  (Qué variables más influyen en cantidad_contratos)\n")
    for idx, row in feature_importance.iterrows():
        bar_length = int(row['importance'] * 30)
        bar = '█' * bar_length
        print(f"  {row['feature']:25s}: {bar:30s} {row['importance']:.4f}")

elif hasattr(mejor_modelo_obj, 'coef_'):
    coefficients = pd.DataFrame({
        'feature': features_regression,
        'coefficient': mejor_modelo_obj.coef_
    }).sort_values('coefficient', key=abs, ascending=False)

    print(f"\n✓ Coeficientes de regresión en {mejor_modelo_nombre}:")
    print("  (Efecto de cada variable en cantidad_contratos)\n")
    for idx, row in coefficients.iterrows():
        sign = '+' if row['coefficient'] > 0 else ''
        print(f"  {row['feature']:25s}: {sign}{row['coefficient']:10.4f}")

# ==============================================================
# Visualización: Comparación de predicciones vs reales
# ==============================================================

y_pred_best = predicciones_modelos[mejor_modelo_nombre]

# Calcular residuales y error
residuales = y_reg - y_pred_best
error_pct = np.abs((y_reg - y_pred_best) / y_reg * 100)

fig, axes = plt.subplots(2, 2, figsize=(15, 11))

# 1. Residuales del mejor modelo
axes[0, 0].scatter(y_reg, residuales, s=120, alpha=0.7, edgecolors='black', linewidth=1.5, color='steelblue')
axes[0, 0].axhline(y=0, color='red', linestyle='--', linewidth=2, label='Residual = 0')
axes[0, 0].set_xlabel('Valores reales (cantidad_contratos)', fontweight='bold', fontsize=11)
axes[0, 0].set_ylabel('Residuales (Real - Predicho)', fontweight='bold', fontsize=11)
axes[0, 0].set_title(f'Análisis de Residuales - {mejor_modelo_nombre}', fontweight='bold', fontsize=12)
axes[0, 0].grid(True, alpha=0.3)
axes[0, 0].legend()

# 2. Actual vs Predicho
r2_best = r2_score(y_reg, y_pred_best)
axes[0, 1].scatter(y_reg, y_pred_best, s=120, alpha=0.7, edgecolors='black', linewidth=1.5, color='green')
# Línea perfecta
min_val, max_val = y_reg.min(), y_reg.max()
axes[0, 1].plot([min_val, max_val], [min_val, max_val], 'r--', linewidth=2.5, label='Predicción perfecta')
axes[0, 1].set_xlabel('Valores reales', fontweight='bold', fontsize=11)
axes[0, 1].set_ylabel('Predicciones', fontweight='bold', fontsize=11)
axes[0, 1].set_title(f'Actual vs Predicho - {mejor_modelo_nombre}\nR² = {r2_best:.4f}', fontweight='bold', fontsize=12)
axes[0, 1].legend(fontsize=10)
axes[0, 1].grid(True, alpha=0.3)

# 3. Comparación de modelos - R²
df_res_plot = df_resultados_sorted.head(6)
colors = ['darkgreen' if m == mejor_modelo_nombre else 'steelblue' for m in df_res_plot['Modelo']]
bars = axes[1, 0].barh(df_res_plot['Modelo'], df_res_plot['R²'], color=colors, alpha=0.8, edgecolor='black', linewidth=1.5)
axes[1, 0].set_xlabel('R² Score', fontweight='bold', fontsize=11)
axes[1, 0].set_title('Comparación de Modelos - R² (Top 6)', fontweight='bold', fontsize=12)
axes[1, 0].set_xlim([0.5, 1.0])
axes[1, 0].grid(True, alpha=0.3, axis='x')
# Agregar valores en barras
for i, bar in enumerate(bars):
    width = bar.get_width()
    axes[1, 0].text(width - 0.02, bar.get_y() + bar.get_height()/2,
                   f'{width:.3f}', ha='right', va='center', fontweight='bold', fontsize=9)

# 4. Serie temporal: Real vs Predicho
anos = df_integrado['anio'].values
axes[1, 1].plot(anos, y_reg, 'o-', linewidth=2.5, markersize=10, label='Real (histórico)', color='navy')
axes[1, 1].plot(anos, y_pred_best, 's--', linewidth=2.5, markersize=8, label=f'Predicho ({mejor_modelo_nombre})', color='orange')
axes[1, 1].fill_between(anos, y_reg, y_pred_best, alpha=0.2, color='gray', label='Error')
axes[1, 1].set_xlabel('Año', fontweight='bold', fontsize=11)
axes[1, 1].set_ylabel('Cantidad de contratos', fontweight='bold', fontsize=11)
axes[1, 1].set_title('Evolución temporal: Real vs Predicho', fontweight='bold', fontsize=12)
axes[1, 1].legend(fontsize=10, loc='upper left')
axes[1, 1].grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('regression_models_evaluation.png', dpi=150, bbox_inches='tight')
plt.show()

print(f"\n✓ Gráfico guardado: regression_models_evaluation.png")

# ==============================================================
# Análisis de errores por año
# ==============================================================

error_por_año = pd.DataFrame({
    'anio': df_integrado['anio'],
    'real': y_reg.values,
    'predicho': y_pred_best,
    'error_absoluto': np.abs(y_reg.values - y_pred_best),
    'error_pct': np.abs((y_reg.values - y_pred_best) / y_reg.values * 100)
})

print(f"\n✓ Análisis de errores por año:")
print("\nAño  | Real         | Predicho     | Error (Δ)    | Error (%)")
print("-"*70)
for _, row in error_por_año.iterrows():
    print(f"{int(row['anio'])} | {row['real']:12,.0f} | {row['predicho']:12,.0f} | {row['error_absoluto']:12,.0f} | {row['error_pct']:7.2f}%")

print(f"\nEstadísticos de error:")
print(f"  Promedio Error Absoluto: {error_por_año['error_absoluto'].mean():,.0f} contratos")
print(f"  Promedio Error %: {error_por_año['error_pct'].mean():.2f}%")
print(f"  Máximo Error Absoluto: {error_por_año['error_absoluto'].max():,.0f} ({error_por_año.loc[error_por_año['error_absoluto'].idxmax(), 'anio']:.0f})")
print(f"  Desviación estándar de errores: {error_por_año['error_absoluto'].std():,.0f}")

# ==============================================================
# Guardar resultados
# ==============================================================

df_integrado['cantidad_predicha'] = y_pred_best
df_integrado['error_cantidad'] = error_por_año['error_absoluto'].values
df_integrado['error_pct_cantidad'] = error_por_año['error_pct'].values

print(f"\n✓ Predicciones agregadas a df_integrado")
print(f"  Columnas nuevas: 'cantidad_predicha', 'error_cantidad', 'error_pct_cantidad'")

print("\n" + "="*70)
print("FASE 7B: SUPERVISED LEARNING - RESUMEN")
print("="*70)
print(f"\n✓ Mejor modelo: {mejor_modelo_nombre}")
print(f"  Performance: R²={r2_best:.4f} ({r2_best*100:.1f}% varianza explicada)")
print(f"  Error promedio: {error_por_año['error_pct'].mean():.2f}%")
print(f"  Error máximo: {error_por_año['error_pct'].max():.2f}% (año {int(error_por_año.loc[error_por_año['error_pct'].idxmax(), 'anio'])})")
print(f"\n✓ Dataset actualizado con predicciones")
print(f"✓ Dataset LISTO para FORECASTING (Celda 32)")

# CELDA 32: TIME SERIES FORECASTING & PROJECTIONS (VERSIÓN CORREGIDA)
# ==============================================================
# Proyectar cantidad_contratos para 2026 usando múltiples enfoques
# Métodos: Linear Trend, Regresión Multivariada, Exponential Smoothing, ENSEMBLE

# IMPORTS COMPLETOS
from sklearn.linear_model import LinearRegression
from scipy import stats
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

print("FASE 8: TIME SERIES FORECASTING & PROJECTIONS")
print("="*70)

# ==============================================================
# MÉTODO 1: REGRESIÓN LINEAL SIMPLE (Trend Extrapolation)
# ==============================================================

# Variable temporal: índice (0=2016, 9=2025)
t = np.arange(len(df_integrado))
t_2026 = np.array([10])  # 2026 es el siguiente año

# Regresión: cantidad_contratos vs tiempo
X_time = t.reshape(-1, 1)
y_cantidad = df_integrado['cantidad_contratos'].values

modelo_trend = LinearRegression()
modelo_trend.fit(X_time, y_cantidad)

# Predicción 2026
pred_2026_trend = modelo_trend.predict(t_2026.reshape(-1, 1))[0]

# Calcular intervalo de confianza (IC 95%)
residuos = y_cantidad - modelo_trend.predict(X_time)
std_residuos = np.std(residuos)
ic_trend = 1.96 * std_residuos  # IC 95%

r2_trend = modelo_trend.score(X_time, y_cantidad)

print("\n✓ MÉTODO 1: LINEAR TREND EXTRAPOLATION")
print(f"  Ecuación: Cantidad = {modelo_trend.intercept_:,.0f} + {modelo_trend.coef_[0]:,.0f} × Año")
print(f"  R²: {r2_trend:.4f}")
print(f"\n  Proyección 2026: {pred_2026_trend:,.0f} contratos")
print(f"  Intervalo 95%: [{pred_2026_trend - ic_trend:,.0f}, {pred_2026_trend + ic_trend:,.0f}]")
print(f"  Cambio respecto 2025: {pred_2026_trend - y_cantidad[-1]:+,.0f} ({(pred_2026_trend/y_cantidad[-1]-1)*100:+.1f}%)")

# ==============================================================
# MÉTODO 2: REGRESIÓN CON VARIABLES MACROECONÓMICAS
# ==============================================================
# Proyectar con modelo de Celda 31 y variables macro escaladas

# Verificar que mejor_modelo_obj existe (de Celda 31)
try:
    modelo_reg_exists = mejor_modelo_obj is not None
except NameError:
    modelo_reg_exists = False
    print("\n⚠️  ADVERTENCIA: mejor_modelo_obj no encontrado")
    print("   Asegúrese de ejecutar Celda 31 antes de Celda 32")

if modelo_reg_exists:
    # Supuesto: proyectar variables macroeconómicas con trend lineal también
    macro_vars = ['pib_billones_cop', 'inflacion_anual_pct', 'tcr_cop_usd', 'desempleo_pct']

    proyecciones_macro_2026 = {}

    print("\n✓ MÉTODO 2: REGRESIÓN MULTIVARIADA")
    print("  Proyectando variables macroeconómicas 2026...")

    for var in macro_vars:
        y_macro = df_integrado[var].values
        modelo_macro = LinearRegression()
        modelo_macro.fit(X_time, y_macro)
        proyecciones_macro_2026[var] = modelo_macro.predict(t_2026.reshape(-1, 1))[0]

    # Construir X para predicción 2026
    X_2026_macro = np.array([[
        proyecciones_macro_2026['pib_billones_cop'],
        proyecciones_macro_2026['inflacion_anual_pct'],
        proyecciones_macro_2026['tcr_cop_usd'],
        proyecciones_macro_2026['desempleo_pct'],
        df_integrado['pct_valor_A'].mean(),  # Usar promedio histórico
        df_integrado['pct_valor_B'].mean(),
        df_integrado['pct_valor_C'].mean()
    ]])

    # Usar mejor modelo de Celda 31 para predicción
    pred_2026_macro = mejor_modelo_obj.predict(X_2026_macro)[0]

    # IC basado en error histórico del modelo
    error_historico_mae = df_integrado['error_cantidad'].mean()
    ic_macro = 1.96 * error_historico_mae

    print(f"  Valores macro proyectados para 2026:")
    for var, val in proyecciones_macro_2026.items():
        print(f"    {var:25s}: {val:12.4f}")

    print(f"\n  Predicción 2026: {pred_2026_macro:,.0f} contratos")
    print(f"  Intervalo 95%: [{pred_2026_macro - ic_macro:,.0f}, {pred_2026_macro + ic_macro:,.0f}]")
    print(f"  Cambio respecto 2025: {pred_2026_macro - y_cantidad[-1]:+,.0f} ({(pred_2026_macro/y_cantidad[-1]-1)*100:+.1f}%)")
else:
    pred_2026_macro = pred_2026_trend  # Fallback
    ic_macro = ic_trend
    print("\n✗ MÉTODO 2 saltado (ejecutar Celda 31 primero)")

# ==============================================================
# MÉTODO 3: EXPONENTIAL SMOOTHING (Suavizado exponencial)
# ==============================================================

alpha = 0.3  # Parámetro de suavizado (peso a observación más reciente)
pred_exp_smooth = [y_cantidad[0]]

for t_idx in range(1, len(y_cantidad)):
    pred_exp_smooth.append(alpha * y_cantidad[t_idx-1] + (1-alpha) * pred_exp_smooth[t_idx-1])

# Proyectar 2026
pred_2026_exp = alpha * y_cantidad[-1] + (1-alpha) * pred_exp_smooth[-1]

# IC basado en varianza histórica de residuos
residuos_exp = y_cantidad[1:] - np.array(pred_exp_smooth[:-1])
ic_exp = 1.96 * np.std(residuos_exp)

print("\n✓ MÉTODO 3: EXPONENTIAL SMOOTHING (α=0.3)")
print(f"  Parámetro α=0.3 da peso balanceado a histórico vs reciente")
print(f"  Predicción 2026: {pred_2026_exp:,.0f} contratos")
print(f"  Intervalo 95%: [{pred_2026_exp - ic_exp:,.0f}, {pred_2026_exp + ic_exp:,.0f}]")
print(f"  Cambio respecto 2025: {pred_2026_exp - y_cantidad[-1]:+,.0f} ({(pred_2026_exp/y_cantidad[-1]-1)*100:+.1f}%)")

# ==============================================================
# MÉTODO 4: PROMEDIO PONDERADO DE MÉTODOS
# ==============================================================

# Ponderación: dar mayor peso al método multivariado (mejores R²)
pesos = {'trend': 0.25, 'macro': 0.50, 'exp_smooth': 0.25}

pred_2026_ensemble = (
    pesos['trend'] * pred_2026_trend +
    pesos['macro'] * pred_2026_macro +
    pesos['exp_smooth'] * pred_2026_exp
)

# IC: promedio ponderado de los ICs
ic_ensemble = np.sqrt(
    (pesos['trend']*ic_trend)**2 +
    (pesos['macro']*ic_macro)**2 +
    (pesos['exp_smooth']*ic_exp)**2
)

print("\n✓ MÉTODO 4: ENSEMBLE (Promedio ponderado)")
print(f"  Pesos utilizados:")
print(f"    - Linear Trend: {pesos['trend']*100:.0f}%")
print(f"    - Regresión Multivariada: {pesos['macro']*100:.0f}% (mayor peso por mejor R²)")
print(f"    - Exponential Smoothing: {pesos['exp_smooth']*100:.0f}%")
print(f"\n  Predicción 2026: {pred_2026_ensemble:,.0f} contratos")
print(f"  Intervalo 95%: [{pred_2026_ensemble - ic_ensemble:,.0f}, {pred_2026_ensemble + ic_ensemble:,.0f}]")
print(f"  Cambio respecto 2025: {pred_2026_ensemble - y_cantidad[-1]:+,.0f} ({(pred_2026_ensemble/y_cantidad[-1]-1)*100:+.1f}%)")

# ==============================================================
# CREAR DATAFRAME DE PROYECCIONES
# ==============================================================

df_proyecciones = pd.DataFrame({
    'Método': ['Linear Trend', 'Regresión Multivariada', 'Exponential Smoothing', 'ENSEMBLE (Recomendado)'],
    'Predicción 2026': [pred_2026_trend, pred_2026_macro, pred_2026_exp, pred_2026_ensemble],
    'IC_Inferior': [
        pred_2026_trend - ic_trend,
        pred_2026_macro - ic_macro,
        pred_2026_exp - ic_exp,
        pred_2026_ensemble - ic_ensemble
    ],
    'IC_Superior': [
        pred_2026_trend + ic_trend,
        pred_2026_macro + ic_macro,
        pred_2026_exp + ic_exp,
        pred_2026_ensemble + ic_ensemble
    ],
    'Cambio_Pct': [
        (pred_2026_trend/y_cantidad[-1]-1)*100,
        (pred_2026_macro/y_cantidad[-1]-1)*100,
        (pred_2026_exp/y_cantidad[-1]-1)*100,
        (pred_2026_ensemble/y_cantidad[-1]-1)*100
    ]
})

print("\n" + "="*80)
print("RESUMEN DE PROYECCIONES PARA 2026")
print("="*80)
print(df_proyecciones.to_string(index=False))

# ==============================================================
# VISUALIZACIÓN: PROYECCIONES E INTERVALOS DE CONFIANZA
# ==============================================================

fig, ax = plt.subplots(figsize=(15, 7))

anos_historico = df_integrado['anio'].values
cantidad_historica = y_cantidad

# Línea histórica principal
ax.plot(anos_historico, cantidad_historica, 'o-', linewidth=3, markersize=10,
        label='Datos históricos (2016-2025)', color='navy', zorder=3)

# Proyecciones individuales
metodos_plot = [
    ('trend', pred_2026_trend, ic_trend, 'orange'),
    ('macro', pred_2026_macro, ic_macro, 'green'),
    ('exp_smooth', pred_2026_exp, ic_exp, 'purple'),
]

y_positions_scatter = 2026.0
for i, (metodo, pred, ic, color) in enumerate(metodos_plot):
    offset = (i - 1) * 0.12  # Pequeño offset para evitar superposición
    ax.scatter(2026 + offset, pred, s=120, marker='s', color=color,
              edgecolor='black', linewidth=1.5, label=f'{metodo}', zorder=4, alpha=0.7)
    ax.vlines(2026 + offset, pred - ic, pred + ic, colors=color, linewidth=1.5, alpha=0.5)

# Proyección ENSEMBLE (DESTACADA - estrella grande)
ax.scatter(2026, pred_2026_ensemble, s=500, marker='*', color='red',
          edgecolor='black', linewidth=2.5, label='ENSEMBLE (Recomendado)', zorder=10)
ax.vlines(2026, pred_2026_ensemble - ic_ensemble, pred_2026_ensemble + ic_ensemble,
         colors='red', linewidth=3, alpha=0.8, linestyles='dashed')

# Banda de incertidumbre del ensemble
ax.fill_between([2025.8, 2026.2],
               pred_2026_ensemble - ic_ensemble,
               pred_2026_ensemble + ic_ensemble,
               color='red', alpha=0.15, label='IC 95% (ENSEMBLE)')

# Extender línea de tendencia (opcional, visual)
t_extended = np.array([0, 10]).reshape(-1, 1)
y_trend_extended = modelo_trend.predict(t_extended)
anos_extended = np.array([2016, 2026])
ax.plot(anos_extended, y_trend_extended, '--', linewidth=1.5, color='gray', alpha=0.4, label='Tendencia lineal')

# Formatting
ax.set_xlabel('Año', fontsize=13, fontweight='bold')
ax.set_ylabel('Cantidad de contratos', fontsize=13, fontweight='bold')
ax.set_title('Proyecciones de Cantidad de Contratos - 2026\n(Líneas verticales muestran intervalos de confianza 95%)',
            fontsize=14, fontweight='bold')
ax.legend(loc='upper left', fontsize=11, framealpha=0.95)
ax.grid(True, alpha=0.3, linestyle='--')
ax.set_xlim([2015.5, 2026.5])

# Anotaciones de últimos años históricos
for i in range(len(anos_historico)-3, len(anos_historico)):
    idx = i
    ano = int(anos_historico[idx])
    cantidad = cantidad_historica[idx]
    ax.annotate(f'{cantidad:,.0f}',
               xy=(ano, cantidad),
               xytext=(0, 10), textcoords='offset points',
               fontsize=9, ha='center',
               bbox=dict(boxstyle='round,pad=0.3', facecolor='yellow', alpha=0.3),
               fontweight='bold')

# Anotación grande para ENSEMBLE
ensemble_text = f'ENSEMBLE\n{pred_2026_ensemble:,.0f}\n(IC: [{pred_2026_ensemble - ic_ensemble:,.0f}, {pred_2026_ensemble + ic_ensemble:,.0f}])'
ax.annotate(ensemble_text,
           xy=(2026, pred_2026_ensemble),
           xytext=(25, 40), textcoords='offset points',
           fontsize=11, fontweight='bold',
           bbox=dict(boxstyle='round,pad=0.6', facecolor='red', alpha=0.15, edgecolor='red', linewidth=2),
           arrowprops=dict(arrowstyle='->', connectionstyle='arc3,rad=0.3', color='red', lw=2.5))

plt.tight_layout()
plt.savefig('forecasting_2026_projections.png', dpi=150, bbox_inches='tight')
plt.show()

print(f"\n✓ Gráfico guardado: forecasting_2026_projections.png")

# ==============================================================
# GUARDAR PROYECCIONES EN DATASET
# ==============================================================

df_2026 = pd.DataFrame({
    'anio': [2026],
    'cantidad_contratos_real': [np.nan],  # Desconocido
    'cantidad_contratos_predicha_ensemble': [pred_2026_ensemble],
    'cantidad_contratos_predicha_trend': [pred_2026_trend],
    'cantidad_contratos_predicha_macro': [pred_2026_macro],
    'cantidad_contratos_predicha_exp': [pred_2026_exp],
    'ic_inferior_ensemble': [pred_2026_ensemble - ic_ensemble],
    'ic_superior_ensemble': [pred_2026_ensemble + ic_ensemble],
    'metodo_recomendado': ['ENSEMBLE: Multivariado (50%) + Trend (25%) + Exponential (25%)']
})

print(f"\n✓ Proyecciones para 2026 guardadas")

print(f"\n" + "="*70)
print("PROYECCIÓN FINAL PARA 2026")
print("="*70)
print(f"\n✓ Predicción ENSEMBLE RECOMENDADA: {pred_2026_ensemble:,.0f} contratos")
print(f"  Intervalo de confianza (95%): [{pred_2026_ensemble - ic_ensemble:,.0f}, {pred_2026_ensemble + ic_ensemble:,.0f}]")
print(f"  Crecimiento esperado: {(pred_2026_ensemble/y_cantidad[-1]-1)*100:+.1f}% respecto a 2025")
print(f"  Margen de error (IC): ±{ic_ensemble:,.0f} contratos")

print("\n✓ Interpretación:")
print(f"  - El modelo es {df_resultados_sorted.iloc[0]['R²']*100:.0f}% confiable en explicar la variación histórica")
print(f"  - La proyección se basa en continuidad de tendencias históricas")
print(f"  - El intervalo de confianza refleja incertidumbre en la predicción")

print("\n" + "="*70)
print("FASE 8: FORECASTING - RESUMEN")
print("="*70)
print(f"\n✓ 4 métodos de pronóstico evaluados")
print(f"✓ Proyección ENSEMBLE recomendada: {pred_2026_ensemble:,.0f} contratos")
print(f"✓ Intervalo de confianza 95%: ±{ic_ensemble:,.0f} contratos")
print(f"✓ Error histórico promedio: {df_integrado['error_pct_cantidad'].mean():.2f}%")
print(f"\n✓ Dataset listo para VISUALIZACIONES FINALES (Celda 33)")